-- MySQL Script generated by MySQL Workbench
-- Mon Sep 29 15:09:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema questionario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `questionario` ;

-- -----------------------------------------------------
-- Schema questionario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `questionario` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `questionario` ;

-- -----------------------------------------------------
-- Table `motivacao_diaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `motivacao_diaria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `motivacao_diaria` (
  `idmotivacao_diaria` INT NOT NULL AUTO_INCREMENT,
  `conquistar_sonhos` INT NULL,
  `reconhecimento` INT NULL,
  `estar_com_quem_ama` INT NULL,
  `cumprir_obrigacoes` INT NULL,
  PRIMARY KEY (`idmotivacao_diaria`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `regulacao_emocional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regulacao_emocional` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `regulacao_emocional` (
  `idregulacao_emocional` INT NOT NULL AUTO_INCREMENT,
  `lido_bem` INT NULL,
  `bem_com_dificuldade` INT NULL,
  `com_dificuldade` INT NULL,
  `nao_lida_bem` INT NULL,
  PRIMARY KEY (`idregulacao_emocional`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `regulacao_emocional_has_relacao_familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regulacao_emocional_has_relacao_familiar` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `regulacao_emocional_has_relacao_familiar` (
  `regulacao_emocional_idregulacao_emocional` INT NOT NULL,
  `relacao_familiar_idrelacao_familiar` INT NOT NULL,
  PRIMARY KEY (`regulacao_emocional_idregulacao_emocional`, `relacao_familiar_idrelacao_familiar`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `relacao_familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relacao_familiar` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `relacao_familiar` (
  `idrelacao_familiar` INT NOT NULL AUTO_INCREMENT,
  `muito_proximo` INT NULL,
  `proximo_dificultado` INT NULL,
  `distante` INT NULL,
  `inexistente_muito_distante` INT NULL,
  PRIMARY KEY (`idrelacao_familiar`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `relacao_familiar_has_satisfacao_com_quem_e`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relacao_familiar_has_satisfacao_com_quem_e` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `relacao_familiar_has_satisfacao_com_quem_e` (
  `relacao_familiar_idrelacao_familiar` INT NOT NULL,
  `satisfacao_com_quem_e_idsatisfacao_com_quem_e` INT NOT NULL,
  PRIMARY KEY (`relacao_familiar_idrelacao_familiar`, `satisfacao_com_quem_e_idsatisfacao_com_quem_e`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `relcao_consigo_mesmo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relcao_consigo_mesmo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `relcao_consigo_mesmo` (
  `idrelcao_consigo_mesmo` INT NOT NULL AUTO_INCREMENT,
  `confiante` INT NULL,
  `razoavel` INT NULL,
  `pouco` INT NULL,
  `inseguro` INT NULL,
  PRIMARY KEY (`idrelcao_consigo_mesmo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `relcao_consigo_mesmo_has_motivacao_diaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relcao_consigo_mesmo_has_motivacao_diaria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `relcao_consigo_mesmo_has_motivacao_diaria` (
  `relcao_consigo_mesmo_idrelcao_consigo_mesmo` INT NOT NULL,
  `motivacao_diaria_idmotivacao_diaria` INT NOT NULL,
  PRIMARY KEY (`relcao_consigo_mesmo_idrelcao_consigo_mesmo`, `motivacao_diaria_idmotivacao_diaria`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `satisfacao_com_quem_e`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `satisfacao_com_quem_e` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `satisfacao_com_quem_e` (
  `idsatisfacao_com_quem_e` INT NOT NULL AUTO_INCREMENT,
  `sim` INT NULL,
  `razoavel` INT NULL,
  `pouo` INT NULL,
  `nada` INT NULL,
  PRIMARY KEY (`idsatisfacao_com_quem_e`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `satisfacao_com_quem_e_has_relcao_consigo_mesmo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `satisfacao_com_quem_e_has_relcao_consigo_mesmo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `satisfacao_com_quem_e_has_relcao_consigo_mesmo` (
  `satisfacao_com_quem_e_idsatisfacao_com_quem_e` INT NOT NULL,
  `relcao_consigo_mesmo_idrelcao_consigo_mesmo` INT NOT NULL,
  PRIMARY KEY (`satisfacao_com_quem_e_idsatisfacao_com_quem_e`, `relcao_consigo_mesmo_idrelcao_consigo_mesmo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sentindo_hoje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentindo_hoje` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sentindo_hoje` (
  `idsentindo_hoje` INT NOT NULL AUTO_INCREMENT,
  `muito_bem` INT NULL,
  `bem` INT NULL,
  `razoavel` INT NULL,
  `mal` INT NULL,
  PRIMARY KEY (`idsentindo_hoje`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sentindo_hoje_has_sono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sentindo_hoje_has_sono` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sentindo_hoje_has_sono` (
  `sentindo_hoje_idsentindo_hoje` INT NOT NULL,
  `sono_idsono` INT NOT NULL,
  PRIMARY KEY (`sentindo_hoje_idsentindo_hoje`, `sono_idsono`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sono` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sono` (
  `idsono` INT NOT NULL AUTO_INCREMENT,
  `oito_dez` INT NULL,
  `oito` INT NULL,
  `oito_tres` INT NULL,
  `muito_pouco` INT NULL,
  `suficiente` INT NULL,
  PRIMARY KEY (`idsono`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sono_has_regulacao_emocional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sono_has_regulacao_emocional` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sono_has_regulacao_emocional` (
  `sono_idsono` INT NOT NULL,
  `regulacao_emocional_idregulacao_emocional` INT NOT NULL,
  PRIMARY KEY (`sono_idsono`, `regulacao_emocional_idregulacao_emocional`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
